name: "On Feature/Hotfix PR opened: Populate description from issue"
on:
  pull_request:
    types: [ opened, reopened ] 

jobs:
  create_pr_for_feature_push:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - uses: actions/github-script@v5
        id: update_pr
        if: ${{ (github.event.pull_request.base.ref == 'develop' ||  github.event.pull_request.base.ref == 'main') && (startsWith(github.event.pull_request.head.ref, 'feature/') || startsWith(github.event.pull_request.head.ref, 'hotfix/') ) }}
        with:
          result-encoding: string
          script: |
            const [branchType, number, ...name] = "${{ github.event.pull_request.head.ref }}".split("/")
            console.log(`${branchType}, issue ${number}`)
            const issueResp = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
            });
            
            console.log(`issueResp = ${JSON.stringify(issueResp)}`)
            
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: "${{ github.event.number }}",
              body: (
                "${{ github.event.pull_request.body }}\n\n" +
                `## [Issue #${number}](https://github.com/ryanmarks/automated-gitflow/issues/${number})\n\n` +
                issueResp["data"]["body"]
              ),
              issue: issueResp["data"]["number"] // No title needed when an issue gets linked
            });
            
            return number

      - uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.update_pr.outputs.result }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `PR created: https://github.com/${context.repo.owner}/${context.repo.repo}/pull/${{ github.event.number }}`
            })
