on:
  pull_request:
    types: [ created, reopened ] 

jobs:
  create_pr_for_feature_push:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - uses: actions/github-script@v5
        if: ${{ (github.event.base.ref == 'develop' ||  github.event.base.ref == 'main') && (startsWith(github.event.head.ref, 'feature/') || startsWith(github.event.head.ref, 'hotfix/') ) }}
        with:
          script: |
            const [branchType, number, ...name] = "${{ github.event.head.ref }}".split("/")
            console.log(`${branchType}, issue ${number}`)
            const issueResp = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
            });
            
            console.log(`issueResp = ${JSON.stringify(issueResp)}`)
            
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: "${{ github.event.number }}",
              body: issueResp["data"]["body"] + "\n\n ${{ github.event.body }}",
              issue: issueResp["data"]["number"] // No title needed when an issue gets linked
            });
