on:
  issues:
    types:
      - labeled

jobs:
  create_branch_for_ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        if: ${{ ( github.event.label.name == 'in progress' || github.event.label.name == 'hotfix' ) && !github.event.issue.pull_request }}
        with:
          script: |
            const matchingFeatureBranchesPromise = github.rest.git.listMatchingRefs({
              owner: context.repo.owner, 
              repo: context.repo.repo,
              ref: "heads/feature/${{ github.event.issue.number }}",
            });
            
            const matchingHotfixBranchesPromise = github.rest.git.listMatchingRefs({
              owner: context.repo.owner, 
              repo: context.repo.repo,
              ref: "heads/hotfix/${{ github.event.issue.number }}",
            });
            
            const branchExists = Promise.all([
              matchingFeatureBranchesPromise,
              matchingHotfixBranchesPromise
            ]).then((featureResp, hotfixResp) => {
              console.log(`featureResp = ${JSON.stringify(featureResp)}`)
              console.log(`hotfixResp = ${JSON.stringify(hotfixResp)}`)
              
              return (featureResp.length || hotfixResp.length 
                        ? "Branch exists"
                        : false
                      )
            })
            
            
      - uses: actions/github-script@v5
        if: ${{ !steps.set-result.outputs.result }}
        with:
          script: |
            const baseRef = "${{ github.event.label.name == 'hotfix' && 'heads/main' || 'heads/develop' }}"
            
            const shaResp = await github.rest.git.getRef({ 
              owner: context.repo.owner, 
              repo: context.repo.repo,
              ref: baseRef,
            })

            console.log(`shaResp = ${shaResp}`)
            const branchPrefix = "${{ github.event.label.name == 'hotfix' && 'hotfix/' || 'feature/' }}"
            const newBranchRef = `refs/heads/${branchPrefix}${{ github.event.issue.number }}/${ "${{ github.event.issue.title }}".toLowerCase().replace(/[\.\~\^\:\t/\\]/g, "").split(/\W+/).join("-")}`
            console.log(`newBranchRef = ${newBranchRef}`)
            const newRefResp = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: newBranchRef,
              sha: shaResp["data"]["object"]["sha"],
            })





