on:
  issues:
    types:
      - labeled

jobs:
  create_branch_for_ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        if: ${{ github.event.label.name == 'in progress' && !github.event.issue.pull_request }}
        with:
          script: |
            const shaResp = await github.rest.git.getRef({ 
              owner: context.repo.owner, 
              repo: context.repo.repo,
              ref: "heads/develop",
            })
            console.log(`shaResp = ${shaResp}`)
            const newBranchRef = `refs/heads/${{ github.event.issue.number }}-${ "${{ github.event.issue.title }}".toLowerCase().replace(/[\.\~\^\:\t/\\]/g, "").split(/\W+/).join("-")}`
            console.log(`newBranchRef = ${newBranchRef}`)
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: newBranchRef,
              sha: shaResp["data"]["object"]["sha"],
            })
